### ISSUE TITLE
j4125下pve7.1-8核显直通失败

### ISSUE THREAD

**Issue by crazyshitass** [xiangfeidexiaohuo/ProxmoxVE-7.0-DIY#1]
你好，按照教程操作了直通，无法启动黑群晖（DSM7.0.1），报错如下：大概是什么原因？
kvm: -device vfio-pci,host=0000:00:02.0,id=hostpci1,bus=pci.0,addr=0x2: vfio 0000:00:02.0: error getting device from group 1: Invalid argument
Verify all devices in group 1 are bound to vfio-<bus> or pci-stub and not already in use
TASK ERROR: start failed: QEMU exited with code 1

**Comment by suyisong** [comment]
是不是在虚拟机里面添加了pcie显卡了？用脚本的方式，就不用手动添加

**Comment by xiangfeidexiaohuo** [comment]
你这是配置文件 手改了吧，4125直通多简单，直接整就成，不用手动改配置文件。你仔细对比下，操作 有木有错误。
