### ISSUE TITLE
奇怪，看不到主板温度

### ISSUE THREAD

**Issue by suyisong** [xiangfeidexiaohuo/ProxmoxVE-7.0-DIY#13]
root@pve:/usr/share/pve-manager# sensors
nvme-pci-0100
Adapter: PCI adapter
Composite:    +35.9°C  (low  =  -0.1°C, high = +74.8°C)
                       (crit = +79.8°C)

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +58.0°C  (high = +86.0°C, crit = +96.0°C)
Core 0:        +54.0°C  (high = +86.0°C, crit = +96.0°C)
Core 1:        +52.0°C  (high = +86.0°C, crit = +96.0°C)
Core 2:        +53.0°C  (high = +86.0°C, crit = +96.0°C)
Core 3:        +57.0°C  (high = +86.0°C, crit = +96.0°C)

没有显示temp1

**Comment by xiangfeidexiaohuo** [comment]
那就没有呗，获取不到，这有啥，硬件千奇百怪的
