### ISSUE TITLE
希望能加入PCIE硬盘的温度显示

### ISSUE THREAD

**Issue by L1cardo** [xiangfeidexiaohuo/ProxmoxVE-7.0-DIY#4]
近期上市的N5105有PCIE硬盘位，PVE 一般是装在PCIE固态上的

最下面显示了PCIE设备的信息，希望作者能添加进去，这么小的改动我就不提交PR了

```bash
root@pve:~# sensors
coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +47.0°C  (high = +105.0°C, crit = +105.0°C)
Core 0:        +45.0°C  (high = +105.0°C, crit = +105.0°C)
Core 1:        +45.0°C  (high = +105.0°C, crit = +105.0°C)
Core 2:        +45.0°C  (high = +105.0°C, crit = +105.0°C)
Core 3:        +45.0°C  (high = +105.0°C, crit = +105.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +27.8°C  (crit = +119.0°C)

nvme-pci-0100
Adapter: PCI adapter
Composite:    +55.9°C  (low  = -273.1°C, high = +90.8°C)
                       (crit = +92.8°C)
Sensor 1:     +55.9°C  (low  = -273.1°C, high = +65261.8°C)
```

**Comment by xiangfeidexiaohuo** [comment]
> 近期上市的N5105有PCIE硬盘位，PVE 一般是装在PCIE固态上的
> 
> 最下面显示了PCIE设备的信息，希望作者能添加进去，这么小的改动我就不提交PR了
> 
> ```shell
> root@pve:~# sensors
> coretemp-isa-0000
> Adapter: ISA adapter
> Package id 0:  +47.0°C  (high = +105.0°C, crit = +105.0°C)
> Core 0:        +45.0°C  (high = +105.0°C, crit = +105.0°C)
> Core 1:        +45.0°C  (high = +105.0°C, crit = +105.0°C)
> Core 2:        +45.0°C  (high = +105.0°C, crit = +105.0°C)
> Core 3:        +45.0°C  (high = +105.0°C, crit = +105.0°C)
> 
> acpitz-acpi-0
> Adapter: ACPI interface
> temp1:        +27.8°C  (crit = +119.0°C)
> 
> nvme-pci-0100
> Adapter: PCI adapter
> Composite:    +55.9°C  (low  = -273.1°C, high = +90.8°C)
>                        (crit = +92.8°C)
> Sensor 1:     +55.9°C  (low  = -273.1°C, high = +65261.8°C)
> ```

抽空写个教程吧，我是没插nvme，所以，一直空着。

**Comment by xiangfeidexiaohuo** [comment]
教程已经增加

**Comment by L1cardo** [comment]
感谢！
