### ISSUE TITLE
请问下有两块nvme固态该怎么修改呢

### ISSUE THREAD

**Issue by lisonglin980** [xiangfeidexiaohuo/ProxmoxVE-7.0-DIY#6]
![image](https://user-images.githubusercontent.com/68982838/178134232-15beec50-1e3f-4034-be5a-8f1238819588.png)
请问下有两块nvme固态该怎么修改呢，温度读取值都是Composite

**Comment by xiangfeidexiaohuo** [comment]
很麻烦，所有的温度要全部改，划不来。
看哪天得空，简单只讲固态这里吧。单独列出来，不然全部改，不现实。

**Comment by xiangfeidexiaohuo** [comment]
> ![image](https://user-images.githubusercontent.com/68982838/178134232-15beec50-1e3f-4034-be5a-8f1238819588.png) 请问下有两块nvme固态该怎么修改呢，温度读取值都是Composite

看这个教程：Proxmox VE 主界面显示温度的另一种方案: JSON格式   依葫芦画瓢，我没2块nvme，没直接写。
