### ISSUE TITLE
打不开提取的bin文件

### ISSUE THREAD

**Issue by HunterLou** [xiangfeidexiaohuo/ProxmoxVE-7.0-DIY#8]
IRFExtractor打不开我文件：Unknown protocol detected

**Comment by xiangfeidexiaohuo** [comment]
gvt嘛，这个你自己琢磨吧，工具就是这样，打不开，要么操作不对，要么是提取的主板bios有问题，一般去官网下同版本的bios就好。

**Comment by HunterLou** [comment]
是的，好像说技嘉的不好改

**Comment by xiangfeidexiaohuo** [comment]
> 是的，好像说技嘉的不好改

技嘉，我朋友有个小雕，死活改不了，貌似是双bios，还是啥的，这东西不是百分百可改。我自测的妖板华擎改了，还有个朋友是华硕，也能改。
